// ---------------------------------------------------------
// Ejercicio 1 — Variables
// Declara tres variables: una con tu nombre, una con tu edad
// y una con tu ciudad. Imprime un mensaje como:
// "Me llamo [nombre], tengo [edad] años y vivo en [ciudad]"
// ---------------------------------------------------------

let nombre = "Kenneth"
let age = "32 años"
let ciudad = "Cancun"

console.log("Me llamo" +" "+ (nombre) +" "+ "tengo"+ " " + (age) + " " + "vivo en" + " " + (ciudad))